version: "3.9"
services:
  app:
    container_name: go-app
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    depends_on:
      - postgres

    ports:
      - "8000:8080"
    volumes:
      - .:/opt/app/api
  postgres:
    container_name: go-db
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: raid2019rr
      POSTGRES_DB: sentry
    volumes:
      - pgdb:/var/lib/postgresql/data

 

volumes:
  pgdb:
